version: '3'
services:
  config:
    build: ./spring-cloud-config-server
    ports:
      - 8888:8888

  limits:
    build: ./limits-service
    ports:
      - 8080:8080

  currency-exchange:
    build: ./currency-exchange-service
    ports:
      - 8000:8000